server:
  port: 8085

spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB}

jwt:
  secret: ${JWT_SECRET}        # ✅ Injected via environment variables
  expiration: 86400000
