server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/planning-db

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    root: INFO
    org.springframework.kafka: INFO
